source/_elephpants/2014-11-27-black-amsterdamphp.md

The name has no space between Amsterdam and PHP :P

AmsterdamPHP Typo

---

source/_elephpants/2014-11-27-black-amsterdamphp.md

Updating AmsPHP

---

source/_elephpants/2015-12-10-multicolored-haphpy.md

Adding this special elePHPant. Don't know how to test that everything is OK.

Adding the HaPHPy Birthday. Fixing #19

---

source/_elephpants/2014-02-06-purple-phpwomen.md

Fixes duplicate image urls

---

source/_elephpants/2016-02-19-blue-shopware.md

Fix issue https://github.com/philipsharp/afieldguidetoelephpants/issues/25.

Add blue shopware elephpant

---

source/_elephpants/2014-10-28-blue-apigility.md
source/_elephpants/2015-06-08-gold-opengoodies.md
source/_others/2015-09-11-gray-hack.md

Added images for Gold, Apigility, and HHVM, as well as info for Apigility.

Added some updates (gold, Apigility, and HHVM)

---

source/_elephpants/2015-10-13-multicolored-haphpy.md

As V. Fanzutti didn't design the pattern and just handcrafted this particular entity, it would be more accurate to use the wording "handcrafted by".
If you don't mind :-)

HaPHPy elePHPant: change wording to more accurate term

---

source/_elephpants/2016-06-24-white-dpc.md

GH-48 Section for White DPC 2016 Elephpant

Add ibuildings DPC 2016 white elephpant

---

source/_elephpants/2014-11-27-black-amsterdamphp.md

Add link to Amsterdam PHP current web shop.

Add Amsterdam PHP current web shop

---

source/_elephpants/2016-10-27-multicolored-phpdiversity.md

Hi!
According to the campaign and his Facebook profile, Peter is from Slovenia.
Thanks.

Peter is Slovenian

---

source/_elephpants/2014-10-28-blue-apigility.md

http://theoatmeal.com/comics/apostrophe

Remove unnecessary apostrophe

---

app/config/sculpin_site.yml
source/_elephpants/2018-04-14-php-yorkshire.md

Move PHP Yorkshire name to name field

---

app/config/sculpin_site.yml
source/_elephpants/2019-06-07-yellow-darkmira.md

https://php.darkmiratour.rocks/2019/elephpant.html

Add Darkmira PHP Tour elePHPant

---

source/_others/2015-09-11-gray-hack.md

See https://github.com/philipsharp/afieldguidetoelephpants/pull/99#discussion_r282108305

Update pHackyderm prototype names

---

app/config/sculpin_site.yml
source/_elephpants/2019-07-31-blue-linuxforphp.md

Not many details yet
https://twitter.com/linuxforphp/status/1156635964363694080

Add Linux for PHP elePHPant

---

source/_elephpants/2017-06-11-blue-cakedc.md

The files are named correctly but the template is not

Fix path to CakeDC photos

---

source/_elephpants/2019-05-14-black-phpstorm.md

https://twitter.com/WyriHaximus/status/1278995558540218368

Update reverse design for PhpStorm elePHPant

---

source/_elephpants/2020-11-28-php8-opengoodies.md

https://twitter.com/faguo/status/1332635786148253697

Add inPHPinity elePHPant

---

source/_elephpants/2020-09-14-blue-confoo.md

https://twitter.com/confooca/status/1305660049944195072

Add Le Foo du Roi elePHPant

---

app/config/sculpin_site.yml
source/_elephpants/2021-10-15-black-mollie.md

No official announcement that I have seen; only mention here:
https://twitter.com/Fabian_ikono/status/1448966334025506837
Not to be confused with [Molly](https://afieldguidetoelephpants.net/#e-truenorthphp-brown-1433203200)

Add Mollie elePHPant
